### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by LoganArnett** [russmatney/lambda-toying#6]
When trying to utilize this lambda setup I get the following Error I assume when trying to run ffmpeg:
```
{ Error: spawn EACCES
at exports._errnoException (util.js:1018:11)
at ChildProcess.spawn (internal/child_process.js:319:11)
at Object.exports.spawn (child_process.js:378:9)
at module.exports (/var/task/node_modules/lambduh-execute/index.js:29:22)
at /var/task/index.js:63:12
at _fulfilled (/var/task/node_modules/q/q.js:854:54)
at self.promiseDispatch.done (/var/task/node_modules/q/q.js:883:30)
at Promise.promise.promiseDispatch (/var/task/node_modules/q/q.js:816:13)
at /var/task/node_modules/q/q.js:624:44
at runSingle (/var/task/node_modules/q/q.js:137:13) code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }
```

**Comment by CptMaumau** [comment]
@LoganArnett `chmod 755 gif2mp4.sh`
